stages:
  - build-app
  - build-app-image

cache:
  paths:
    - src/web/node_modules/

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

services:
  - docker:18.09.7-dind

build-app:
  stage: build-app
  tags:
    - k8s
  image: node:16-alpine3.11
  script:
    - node -v
    - npm -v
    - cd src/web/
    - npm --force install -g yarn
    - yarn --non-interactive
    - yarn build --non-interactive

build-app-image:
  stage: build-app-image
  tags:
    - k8s
  image: docker:stable
  before_script:
    - apk add --no-cache docker-compose
    - docker info
  script:
    - echo "Building docker WEB APP image"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd src/web/
    - docker build -t teamcard-web . -f prod.dockerfile
    - docker tag teamcard-web:latest $CI_REGISTRY_IMAGE/teamcard-web:latest
    - echo "Pushing docker image to registry"
    - docker push $CI_REGISTRY_IMAGE/teamcard-web:latest