stages:
    - build-net
    - build-app
    - build-images
    - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:20.10.16-dind

build-net:
  stage: build-net
  image: mcr.microsoft.com/dotnet/sdk:7.0
  tags:
    - docker
  script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet restore src/backend/TeamCard.sln
    - dotnet build src/backend/TeamCard.sln -c Release

build-app:
  stage: build-app
  tags:
    - docker
  image: node:16-alpine3.11
  script:
    - node -v
    - npm install -g npm@9.2.0
    - npm -v
    - cd src/web
    - npm install
    - npm run ready

build-images:
  stage: build-images
  tags:
    - docker
  image: docker:stable
  before_script:
    - apk add --no-cache docker-compose
    - docker info
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f docker-compose.yml build
    - docker tag teamcard-web:latest $CI_REGISTRY_IMAGE/teamcard-web:latest
    - docker tag teamcard-api:latest $CI_REGISTRY_IMAGE/teamcard-api:latest
    - docker tag teamcard-nginx:latest $CI_REGISTRY_IMAGE/teamcard-nginx:latest
    - docker push $CI_REGISTRY_IMAGE/teamcard-web:latest
    - docker push $CI_REGISTRY_IMAGE/teamcard-api:latest
    - docker push $CI_REGISTRY_IMAGE/teamcard-nginx:latest

deploy:
  stage: deploy
  image: 
     name: bitnami/kubectl:latest
     entrypoint: [""]  
  tags:
    - docker
  environment:
    name: staging
  script:
        - kubectl config get-contexts
        - kubectl config use-context ezlab/kubernetes-agent:leo
        - kubectl apply -f deploy/namespace.yaml
        - kubectl delete secret docker-registry registry-credentials --ignore-not-found --namespace=teamcard
        - kubectl create secret docker-registry registry-credentials --docker-server=$CI_REGISTRY --docker-username=$EZLAB_DEPLOY_USER --docker-password=$EZLAB_DEPLOY_PWD --namespace=teamcard
        - kubectl apply -f deploy
        - kubectl rollout restart deployment teamcard-web-deployment --namespace teamcard
        - kubectl rollout restart deployment teamcard-web-deployment --namespace teamcard
