version: '3.4'

services:
  teamcard-web:
    image: teamcard-web
    build:
      context: src/web/.
      network: host
      dockerfile: Dockerfile
    restart: on-failure
    deploy:
      replicas: 1
    networks:
      - main-network
    ports:
      - "9090:80"

networks:
  main-network:
    driver: bridge